tap "laishulu/homebrew"
brew "agg"
brew "giflib"
brew "little-cms2"
brew "openssl@3"
brew "aria2"
brew "asciinema"
brew "aspell"
brew "automake"
brew "glib"
brew "python@3.14"
brew "llvm"
brew "clangql"
brew "cmake"
brew "gmp"
brew "coreutils"
brew "ctags"
brew "cuetools"
brew "curl"
brew "dbus"
brew "dos2unix"
brew "expat"
brew "fd"
brew "ffmpeg"
brew "flac"
brew "fzf"
brew "mpfr"
brew "gawk"
brew "libmpc"
brew "gcc"
brew "gh"
brew "ghidra", link: false
brew "libiconv"
brew "git"
brew "git-lfs"
brew "gnutls"
brew "gnupg"
brew "gnu-sed"
brew "gopls"
brew "librsvg"
brew "graphviz"
brew "pkgconf"
brew "hadolint"
brew "hugo"
brew "imagemagick"
brew "jansson"
brew "latexml"
brew "libffi"
brew "libgccjit"
brew "libsndfile"
brew "libxml2"
brew "lilypond"
brew "llm"
brew "mailutils"
brew "mas"
brew "ninja"
brew "meson"
brew "msmtp"
brew "mupdf"
brew "ncurses"
brew "neovim"
brew "node"
brew "notmuch"
brew "pandoc"
brew "pinentry-mac"
brew "pipenv"
brew "pipx"
brew "poppler"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python-lsp-server"
brew "qt"
brew "ripgrep"
brew "rust"
brew "rustup"
brew "shfmt"
brew "shntool"
brew "sox"
brew "texinfo"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "typescript-language-server"
brew "uv"
brew "watchexec"
brew "wget"
brew "yapf"
brew "yt-dlp"
brew "zlib"
brew "laishulu/homebrew/macism"
cask "caffeine"
cask "font-cascadia-code-nf"
cask "font-fira-code"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono"
cask "font-jolly-lodger"
cask "font-meslo-for-powerlevel10k"
cask "font-noto-color-emoji"
cask "font-noto-sans-cjk"
cask "font-noto-sans-jp"
cask "font-roboto-mono-nerd-font"
cask "font-source-code-pro"
cask "ghidra"
cask "iterm2"
cask "mactex-no-gui"
cask "paste"
cask "syntax-highlight"
cask "webkinz"
mas "Amphetamine", id: 937984704
mas "Apollo", id: 6448019325
mas "Auto Scroll for Safari", id: 6745405563
mas "Command X", id: 6448461551
mas "CotEditor", id: 1024640650
mas "Declutter", id: 1574021257
mas "Developer", id: 640199958
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Just Press Record", id: 1033342465
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Perplexity", id: 6714467650
mas "Prime Video", id: 545519333
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
