tap "homebrew/bundle"
tap "homebrew/services"
brew "giflib"
brew "libtiff"
brew "autoconf"
brew "automake"
brew "cmake"
brew "coreutils"
brew "dbus"
brew "expat"
brew "fd"
brew "gcc"
brew "gdk-pixbuf"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "gnu-sed"
brew "pkgconf"
brew "hugo"
brew "imagemagick"
brew "jansson"
brew "libffi"
brew "libgccjit"
brew "libiconv"
brew "librsvg"
brew "libxml2"
brew "llm"
brew "llvm"
brew "mailutils"
brew "mas"
brew "msmtp"
brew "mupdf"
brew "ncurses"
brew "node"
brew "notmuch"
brew "pandoc"
brew "pipx"
brew "poppler"
brew "pyenv"
brew "ripgrep"
brew "shfmt"
brew "texinfo"
brew "tree-sitter"
brew "wget"
brew "yt-dlp"
brew "zlib"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "font-jolly-lodger"
cask "font-noto-color-emoji"
cask "font-source-code-pro"
cask "mactex-no-gui"
cask "syntax-highlight"
mas "Amphetamine", id: 937984704
mas "Developer", id: 640199958
mas "iMovie", id: 408981434
mas "Just Press Record", id: 1033342465
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "Prime Video", id: 545519333
mas "Slack", id: 803453959
